url: https://BenBronselaer.github.io
baseurl: 

# Site settings
title: Ben Bronselaer
email: benjamin.bronselaer@noaa.gov
description: "Ben Bronselaer ocean climate"


# Team names, titles and social links
people:
- name:  The Southern Ocean Model Intercomparison Project
  pic: 1
  position: The Southern Ocean Model Intercomparison Project (SOMIP) is an atmosphere-ocean general circulation model (and earth system model) intercomparison project, and is a subset of  <a href="http://www.met.reading.ac.uk/~jonathan/FAFMIP/">FAFMIP</a> . SOMIP is primarily focused on the  <a href="https://www.wcrp-climate.org/wgcm-cmip/wgcm-cmip6">CMIP6</a>  scientific question “How does the Earth System respond to forcing?” with the aim of reducing uncertainties in climate projections of ocean heat and carbon uptake, by defining the role of the Southern Ocean in the climate. Learn more about SOMIP <a href="https://southernocean.arizona.edu/node/42">here</a>


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/BenBronselaer
  - title: instagram
    url: https://www.instagram.com/benbronselaer/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
