url: https://BenBronselaer.github.io
baseurl: 

# Site settings
title: Ben Bronselaer
email: benjamin.bronselaer@noaa.gov
description: "Ben Bronselaer ocean climate"


# Team names, titles and social links
people:
- name:  The Southern Ocean Model Intercomparison Project
  pic: 1
  position: The Southern Ocean Model Intercomparison Project (SOMIP) is an atmosphere-ocean general circulation model (and earth system model) intercomparison project, and is a subset of  <a href="http://www.met.reading.ac.uk/~jonathan/FAFMIP/">FAFMIP</a> . SOMIP is primarily focused on the  <a href="https://www.wcrp-climate.org/wgcm-cmip/wgcm-cmip6">CMIP6</a>  scientific question “How does the Earth System respond to forcing?” with the aim of reducing uncertainties in climate projections of ocean heat and carbon uptake, by defining the role of the Southern Ocean in the climate. Learn more about SOMIP <a href="https://southernocean.arizona.edu/node/42">here</a>.


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: envelope
    url: mailto:benjamin.bronselaer@cantab.net
  - title: twitter
    url: http://twitter.com/BenBronselaer
  - title: instagram
    url: https://www.instagram.com/benbronselaer/
    
    
# Highlighted publications
pubs:
  - title: Something coming soon!
    authors: B Bronselaer, L Zanna
    journal: (2020)
    doi: https://doi.org/10.1038/s41561-019-0502-8
    pic: Nat
  - title: Importance of wind and meltwater for observed chemical and physical changes in the Southern Ocean
    authors: B Bronselaer, J L Russell, M Winton, N L Williams, R M Key, J P Dunne, R A Feely, K S Johnson, J L Sarmiento 
    journal: Nature Geoscience (2020)
    doi: https://doi.org/10.1038/s41586-018-0712-z
    pic: NatGeo
  - title: Change in future climate due to Antarctic meltwater
    authors: B Bronselaer, M Winton, S M Griffies, W J Hurlin, K B Rodgers, O V Sergienko, R J Stouffer, J L Russell
    journal: Nature (2018)
    doi: https://doi.org/10.1038/s41586-018-0712-z
    pic: Nature
  - title: Agreement of CMIP5 Simulated and Observed Ocean Anthropogenic CO2 Uptake
    authors: B Bronselaer, M Winton, J Russell, CL Sabine, S Khatiwala
    journal: Geophysical Research Letters (2017)
    doi: https://doi.org/10.1002/2017GL074435
    pic: GRL
  - title: Southern Ocean carbon-wind stress feedback
    authors: B Bronselaer, L Zanna, DR Munday, J Lowe
    journal: Climate Dynamics (2017)
    doi: https://doi.org/10.1007/s00382-017-4041-y
    pic: CLDY
  - title: The influence of Southern Ocean winds on the North Atlantic carbon sink
    authors: B Bronselaer, L Zanna, DR Munday, J Lowe
    journal: Global Biogeochemical Cycles (2016)
    doi: https://doi.org/10.1002/2015GB005364
    pic: GBC
  - title: Assessing the abilities of CMIP5 models to represent the seasonal cycle of surface ocean pCO2
    authors: DJ Pilcher, SR Brody, L Johnson, B Bronselaer
    journal: Journal of Geophysical Research Oceans (2015)
    doi: https://doi.org/10.1002/2015JC010759
    pic: JGR


# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
