url: https://BenBronselaer.github.io
baseurl: 

# Site settings
title: Ben Bronselaer
email: benjamin.bronselaer@noaa.gov
description: "Ben Bronselaer ocean climate"


# Team names, titles and social links
people:
- name: Southern Ocean Modelling Intercomparison Project
  pic: 1
  position: SOMOIP 


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/BenBronselaer
  - title: instagram
    url: https://www.instagram.com/benbronselaer/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
